"""Retrodiction-gated executable world models for ARC3."""

from .compiler import CompilationResult, CompileIssue, compile_hypotheses
from .lifecycle import (
    MechanicsChangeCandidate,
    MechanicsChangeDomain,
    MechanicsChangeStatus,
    MechanicsEpoch,
    MechanicsEpochStatus,
    MechanicsLifecycle,
)
from .model import (
    AlternativeOutcome,
    EnsemblePrediction,
    ModelCandidate,
    ModelPrediction,
    WorldModelEnsemble,
    make_model_candidate,
)
from .receipts import (
    ConsequenceAssessment,
    ModelReopening,
    PredictionBook,
    PredictionReceipt,
)
from .retrodiction import (
    ModelScore,
    PreservedTransition,
    PromotionStatus,
    RetrodictionArtifact,
    StateResidual,
    compare_states,
    gated_ensemble,
    retrodict,
)
from .rules import (
    AttachmentMode,
    AttachmentRule,
    CollisionBehavior,
    CollisionRule,
    ConditionKind,
    ContactEffectKind,
    ContactRelation,
    ContactRule,
    CoordinateEffectKind,
    CoordinateEffectRule,
    CounterRule,
    MovementRule,
    NoOpRule,
    RuleCondition,
    RuleEffect,
    RuleExecution,
    RulePrimitive,
    SelectionMode,
    SelectionRule,
    ToggleRule,
    TransformationKind,
    TransformationRule,
    execute_rules,
)
from .simulator import SimulatedPath, SimulationResult, simulate_sequence
from .state import Attachment, Cell, SymbolicEntity, SymbolicState

__all__ = [
    "AlternativeOutcome",
    "Attachment",
    "AttachmentMode",
    "AttachmentRule",
    "Cell",
    "CollisionBehavior",
    "CollisionRule",
    "CompilationResult",
    "CompileIssue",
    "ConditionKind",
    "ConsequenceAssessment",
    "ContactEffectKind",
    "ContactRelation",
    "ContactRule",
    "CoordinateEffectKind",
    "CoordinateEffectRule",
    "CounterRule",
    "EnsemblePrediction",
    "MechanicsChangeCandidate",
    "MechanicsChangeDomain",
    "MechanicsChangeStatus",
    "MechanicsEpoch",
    "MechanicsEpochStatus",
    "MechanicsLifecycle",
    "ModelCandidate",
    "ModelPrediction",
    "ModelReopening",
    "ModelScore",
    "MovementRule",
    "NoOpRule",
    "PredictionBook",
    "PredictionReceipt",
    "PreservedTransition",
    "PromotionStatus",
    "RetrodictionArtifact",
    "RuleCondition",
    "RuleEffect",
    "RuleExecution",
    "RulePrimitive",
    "SelectionMode",
    "SelectionRule",
    "SimulatedPath",
    "SimulationResult",
    "StateResidual",
    "SymbolicEntity",
    "SymbolicState",
    "ToggleRule",
    "TransformationKind",
    "TransformationRule",
    "WorldModelEnsemble",
    "compare_states",
    "compile_hypotheses",
    "execute_rules",
    "gated_ensemble",
    "make_model_candidate",
    "retrodict",
    "simulate_sequence",
]
