"""Procedural unseen-rule laboratory with a strict evaluator boundary."""

from .evaluator import (
    EvaluatorEpisode,
    LabEvaluator,
    LabPolicy,
    available_rule_families,
    measure_baseline,
    run_batch,
)
from .models import (
    BaselineMeasurement,
    EpisodeGroundTruth,
    EpisodeRecord,
    EvaluatedStep,
    LabCase,
    LabPartition,
    RuleFamily,
    TransitionTruth,
)
from .rule_change import (
    RULE_CHANGE_ACTIONS,
    RULE_CHANGE_GAME_ID,
    RULE_CHANGE_GRID_SIZE,
    RULE_CHANGE_SEEDS,
    ActionVariant,
    CheckpointBoundary,
    EvaluatedRuleChangeStep,
    PaletteVariant,
    RuleChangeCase,
    RuleChangeCaseKind,
    RuleChangeCheckpointCase,
    RuleChangeEvaluatorEpisode,
    RuleChangeEvaluatorProjection,
    RuleChangeFamily,
    RuleChangeSession,
    RuleChangeTiming,
    RuleChangeTruthReceipt,
    checkpoint_schedule,
    intervention_schedule,
    noise_control_schedule,
    open_rule_change_case,
)
from .session import LabAdapter, LabSession

__all__ = [
    "RULE_CHANGE_ACTIONS",
    "RULE_CHANGE_GAME_ID",
    "RULE_CHANGE_GRID_SIZE",
    "RULE_CHANGE_SEEDS",
    "ActionVariant",
    "BaselineMeasurement",
    "CheckpointBoundary",
    "EpisodeGroundTruth",
    "EpisodeRecord",
    "EvaluatedRuleChangeStep",
    "EvaluatedStep",
    "EvaluatorEpisode",
    "LabAdapter",
    "LabCase",
    "LabEvaluator",
    "LabPartition",
    "LabPolicy",
    "LabSession",
    "PaletteVariant",
    "RuleChangeCase",
    "RuleChangeCaseKind",
    "RuleChangeCheckpointCase",
    "RuleChangeEvaluatorEpisode",
    "RuleChangeEvaluatorProjection",
    "RuleChangeFamily",
    "RuleChangeSession",
    "RuleChangeTiming",
    "RuleChangeTruthReceipt",
    "RuleFamily",
    "TransitionTruth",
    "available_rule_families",
    "checkpoint_schedule",
    "intervention_schedule",
    "measure_baseline",
    "noise_control_schedule",
    "open_rule_change_case",
    "run_batch",
]
