"""Typed, trace-first support for the Wise Scientist play directive."""

from arc3.wise_scientist.frame_witness import (
    PatternLocation,
    PositionChangeKind,
    PositionTransition,
    locate_pattern,
    measure_position_transition,
    require_position_transition,
    require_unique_pattern,
)
from arc3.wise_scientist.journal import WiseEvent, WiseJournal
from arc3.wise_scientist.models import (
    ActCommand,
    ActionAlternative,
    AssessCommand,
    AssessmentKind,
    DecisionRelevance,
    Distinction,
    DistinctionRevision,
    GoalStatus,
    GoalUpdate,
    Prediction,
    RevisionKind,
    ScanCommand,
    Subgoal,
    SubgoalUpdateKind,
    WiseRationale,
)
from arc3.wise_scientist.session import (
    GOVERNING_OBJECTIVE,
    GOVERNING_OBJECTIVE_ID,
    WiseRunPhase,
    WiseScientistRun,
    observation_hash,
    observation_payload,
)

__all__ = [
    "GOVERNING_OBJECTIVE",
    "GOVERNING_OBJECTIVE_ID",
    "ActCommand",
    "ActionAlternative",
    "AssessCommand",
    "AssessmentKind",
    "DecisionRelevance",
    "Distinction",
    "DistinctionRevision",
    "GoalStatus",
    "GoalUpdate",
    "PatternLocation",
    "PositionChangeKind",
    "PositionTransition",
    "Prediction",
    "RevisionKind",
    "ScanCommand",
    "Subgoal",
    "SubgoalUpdateKind",
    "WiseEvent",
    "WiseJournal",
    "WiseRationale",
    "WiseRunPhase",
    "WiseScientistRun",
    "locate_pattern",
    "measure_position_transition",
    "observation_hash",
    "observation_payload",
    "require_position_transition",
    "require_unique_pattern",
]
